<?php
	//get the contents of that file and put them into a variable for use
	$curUsername = (string) file_get_contents($usernameFile);
	$curXp = (int) file_get_contents($xpFile);
	$curProgress = (int) file_get_contents($progressFile);
	$curDmg1 = (int) file_get_contents($Dmg1File);
	$curDmg2 = (int) file_get_contents($Dmg2File);
	$curDmg3 = (int) file_get_contents($Dmg3File);
	$curDmg4 = (int) file_get_contents($Dmg4File);
	$curDmg5 = (int) file_get_contents($Dmg5File);
	$curShd1 = (int) file_get_contents($Shd1File);
	$curShd2 = (int) file_get_contents($Shd2File);
	$curShd3 = (int) file_get_contents($Shd3File);
	$curShd4 = (int) file_get_contents($Shd4File);
	$curShd5 = (int) file_get_contents($Shd5File);
	$curHth1 = (int) file_get_contents($Hth1File);
	$curHth2 = (int) file_get_contents($Hth2File);
	$curHth3 = (int) file_get_contents($Hth3File);
	$curHthNShd1 = (int) file_get_contents($HthNShd1File);
	$curHthNShd2 = (int) file_get_contents($HthNShd2File);
	$curHthNShd3 = (int) file_get_contents($HthNShd3File);
	$curHthNShd4 = (int) file_get_contents($HthNShd4File);
	$curHthNShd5 = (int) file_get_contents($HthNShd5File);
	$curHthNShd6 = (int) file_get_contents($HthNShd6File);
	$curHthStl1 = (int) file_get_contents($HthStl1File);
	$curHthStl2 = (int) file_get_contents($HthStl2File);
	$curHthStl3 = (int) file_get_contents($HthStl3File);
	$curHthStl4 = (int) file_get_contents($HthStl4File);
	$curHthStl5 = (int) file_get_contents($HthStl5File);
	$curShdStl1 = (int) file_get_contents($ShdStl1File);
	$curShdStl2 = (int) file_get_contents($ShdStl2File);
	$curShdStl3 = (int) file_get_contents($ShdStl3File);
	$curShdStl4 = (int) file_get_contents($ShdStl4File);
	$curShdStl5 = (int) file_get_contents($ShdStl5File);
	$curReverse = (int) file_get_contents($ReverseFile);
	$curEng1 = (int) file_get_contents($Eng1File);
	$curEng2 = (int) file_get_contents($Eng2File);
	$curMultX2 = (int) file_get_contents($MultX2File);
	$curMultX3 = (int) file_get_contents($MultX3File);
	$curMultX4 = (int) file_get_contents($MultX4File);
	echo "Current username: " . $curusername;
?>